language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    - php: 5.4
      env: dependencies=lowest

before_script:
  - if [[ $(phpenv version-name) != '5.6' ]]; then composer install -n ; fi
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

script:
  - if [[ $(phpenv version-name) != '5.6' ]]; then vendor/bin/phpunit ; fi
